### PR TITLE
Migrate buffer action server to ROS 2 

### PR DESCRIPTION
**Pull request by jacobperron**
PR contains two commits, the first is in support of the second:
* Add conversion functions for durations 8f95e9b
* Migrate buffer action server to ROS 2 4923ed3

Connects to #158 

This is the first half of #158. I'll follow-up with another PR for the action client.

### CODE REVIEW

**Comment by jacobperron** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8064/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4072/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6570/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7936/)

**Comment by jacobperron** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8079/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4084/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6583/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7956/)

**Review by wjwwood — APPROVED** [review]
lgtm, might want a second review from @tfoote

**Comment by jacobperron** [comment]
I'm going to merge this to get the second PR out. @tfoote I can address any comments from you in a follow-up PR.

**Comment by jacobperron** [comment]
Squashed to keep the new conversion functions and migration commits separate.

**Comment by jacobperron** [comment]
#165 adds the buffer client.

**Pull request merged**
