### PR TITLE
forward declare fromMsg to avoid missing symbols in downstream libraries

### LINKED ISSUE #334: [Linking Bug - Rolling] tf2 geometry msgs converters
Hi,

We were so far using Foxy, that still had the `tf2_geometry_msgs.h` header file in the debian release (0.17.2-1focal.20211011.234834) and had no issue using TEB on the foxy branch. 

I'm now porting to Rolling with `tf2_geometry_msgs` on (0.19.0-1focal.20211105.230706). The header was ported to `tf2_geometry_msgs.hpp` and `tf2_geometry_msgs.h` was deprecated (it gives a warning, but the .h still exists and imports the .hpp).

Note that the compilation gives no error and I stumbled on this when running TEB after starting to run my Behavior Tree, the `controller_server` process died after TEB failed to find a symbol for a `fromMsg` converter.

Tried enabling the tests and the linker error appeared on compilation after a few fixes (mainly just porting Node to LifecycleNode in the homotopy class test)

This is the converter that's not found when compiling:

```cpp
/** \brief Convert a Quaternion message to its equivalent tf2 representation.
 * This function is a specialization of the toMsg template defined in tf2/convert.h.
 * \param in A Quaternion message type.
 * \param out The Quaternion converted to a tf2 type.
 */
inline
void fromMsg(const geometry_msgs::msg::Quaternion & in, tf2::Quaternion & out)
{
  // w at the end in the constructor
  out = tf2::Quaternion(in.x, in.y, in.z, in.w);
}
```

Here's the linker error:

```
--- stderr: teb_local_planner                             
/usr/bin/ld: libteb_local_planner.so: undefined reference to `void tf2::fromMsg<geometry_msgs::msg::Quaternion_<std::allocator<void> >, tf2::Quaternion>(geometry_msgs::msg::Quaternion_<std::allocator<void> > const&, tf2::Quaternion&)'
collect2: error: ld returned 1 exit status
```

Which comes from [teb_local_planner_ros.cpp](https://github.com/rst-tu-dortmund/teb_local_planner/blob/d5fc3fea6e9b77664b53dfefa0261aa9a6635190/teb_local_planner/src/teb_local_planner_ros.cpp#L869)

### PR DESCRIPTION
**Pull request by jcmonteiro**
This PR fixes https://github.com/rst-tu-dortmund/teb_local_planner/issues/334 and mitigates #242 while a proper solution addressing `fromMsg` and other template prototype functions (_e.g._, #427) is not provided.

### Why
Without the forward declaration, the symbol will be undefined in a target that depends on `tf2` and `tf2_geometry_msgs` and includes **first** `tf2/utils.h` and **later** `tf2_geometry_msgs/tf2_geometry_msgs.hpp` since there are inlined functions in `tf2/impl/utils.h` that make use of `fromMsg` with the quaternions as input types.

### Disclaimer
This solution is avoiding the deeper issue where `fromMsg` and other template functions are not being specialized. If, for example, `fromMsg` had been properly specialized in `tf2_geometry_msgs.hpp` for the types `geometry_msgs::msg::Quaternion` and `tf2::Quaternion`, the forward declaration here would be
```cpp
template<>
void fromMsg(const geometry_msgs::msg::Quaternion & in, tf2::Quaternion & out);
```

### Example
One can validate this solution by building a simple library
```cpp
// include/library/library.hpp
#pragma once
namespace library {
void function();
}

```
```cpp
// src/library.cpp
#include "library/library.hpp"
#include <tf2_geometry_msgs/tf2_geometry_msgs.hpp>
#include <tf2/utils.h>

void library::function()
{
  geometry_msgs::msg::Quaternion quat;
  tf2::impl::toQuaternion(quat);
}
```
```cmake
...
add_library(library SHARED src/library.cpp)
...
```
changing the order of the includes and checking the symbols in `liblibrary.so` with
```sh
nm --demangle <path-to-workspace>/build/library/liblibrary.so | grep fromMsg
```
When checking the symbol, one should notice that
- when the symbol is undefined it refers to the template function `tf2::fromMsg<...>(...)`,
- otherwise, it refers to the non-template function `tf2::fromMsg(...)` which is not a specialization of the template function.

### CODE REVIEW

**Review by aprotyas — APPROVED** [review]
I think #427 will take a while to land, so this can be merged for now.

**Comment by aprotyas** [comment]
CI:
Repos file: https://gist.githubusercontent.com/aprotyas/c86851dae9847cc1bcf70351926c5a37/raw/94dd686808cad6b23a27280cb26629b261426080/ros2.repos
Build args: `--packages-above-and-dependencies tf2`
Test args: `--packages-above tf2`
Job: https://ci.ros2.org/job/ci_launcher/9535/

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15814/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10492/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/13478/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16096/)

Note: the failing uncrustify tests were addressed in #486.

**Comment by guilyx** [comment]
Hey @aprotyas, any update on this ?

**Comment by aprotyas** [comment]
It's been a while and the failing tests have been addressed, so I'll re-run CI:

Repos file: https://gist.githubusercontent.com/aprotyas/c86851dae9847cc1bcf70351926c5a37/raw/94dd686808cad6b23a27280cb26629b261426080/ros2.repos
Build args: `--packages-above-and-dependencies tf2`
Test args: `--packages-above tf2`
Job: https://ci.ros2.org/job/ci_launcher/9629/

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15913/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10588/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16237/)

**Comment by aprotyas** [comment]
@ahcorde @clalancette can either of you take a look please?

**Review by ahcorde — APPROVED** [review]

**Comment by aprotyas** [comment]
@jcmonteiro can you rebase your branch on the `ros2` branch? That way https://github.com/ros2/geometry2/commit/de1753cc2319a3d83aedcfefda9eaa6c20c97f1d will be tested as well, addressing the uncrustify failures.

**Comment by aprotyas** [comment]
Re-running CI following the rebase:

Repos file: https://gist.githubusercontent.com/aprotyas/c86851dae9847cc1bcf70351926c5a37/raw/94dd686808cad6b23a27280cb26629b261426080/ros2.repos
Build args: `--packages-above-and-dependencies tf2`
Test args: `--packages-above tf2`
Job: https://ci.ros2.org/job/ci_launcher/9662/
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15948/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10621/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16270/)

**Comment by guilyx** [comment]
@aprotyas hey, any ETA on this ?

**Comment by aprotyas** [comment]
I left this hanging last time, my bad. Okay, @jcmonteiro last rebase request and then I'll run CI.

**Comment by aprotyas** [comment]
Running CI:

Repos file: https://gist.githubusercontent.com/aprotyas/c86851dae9847cc1bcf70351926c5a37/raw/94dd686808cad6b23a27280cb26629b261426080/ros2.repos
Build args: `--packages-above-and-dependencies tf2`
Test args: `--packages-above tf2`
Job: https://ci.ros2.org/job/ci_launcher/10016/
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16373/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10982/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16743/)

**Pull request merged**
