### PR TITLE
Only print out the LOOPING message every 30 seconds.

### PR DESCRIPTION
**Pull request by clalancette**
Partially fixes issue 12, but not linking it so that one doesn't get closed (there is other work to do there).

CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/2891/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/378/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/2330/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/3015/)

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Please use the ROS 2 logging macros for this.

**Comment by clalancette** [comment]
Yeah, that's definitely another thing that needs to be done here.  However, I was going to do that in a separate PR, since there are other files (tf2_monitor.cpp, transform_listener.cpp, etc) that need to be fixed the same way.

**Review by dirk-thomas — CHANGES_REQUESTED** [review]
This PR is only changing the logging to use a custom timer. It should use the specific ROS 2 logging macro for that which already provides that functionality.

**Comment by clalancette** [comment]
Oh, I totally forgot about that.  Right, that makes sense, I'll change it to do that.

**Comment by clalancette** [comment]
New CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/2893/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/380/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/2332/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/3017/)

**Review by dirk-thomas — APPROVED** [review]

**Review by tfoote — APPROVED** [review]

**Comment by mikaelarguedas** [comment]
@clalancette Is there anything preventing from merging this ?

**Comment by clalancette** [comment]
The only reason was those failing tests on MacOS.  It doesn't *seem* like this PR should cause those at all, but I didn't see those failures in other builds, and I haven't had time to investigate further.

**Comment by mikaelarguedas** [comment]
These tests are below in the stack than tf2 so I think it's safe to assume they are unrelated (they also have been failing on the nightlies every other day for a while http://ci.ros2.org/view/nightly/job/nightly_osx_repeated/755/testReport/junit/(root)/TestGetNodeNames__rmw_connext_cpp/test_rcl_get_node_names/).
So I'd advocate for merging this, the alternative is to put this back `in progress` if you plan on investigating.

**Comment by clalancette** [comment]
@mikaelarguedas Thanks for that.  I agree with your assessment; I'm going to merge this now.

**Pull request merged**
