### PR TITLE
Drop PyKDL dependency in tf2_geometry_msgs (backport #509 to foxy)

### PR DESCRIPTION
**Pull request by dawsonc**
This PR supersedes #530, fixing merge conflicts to backport `tf2_geometry_msgs` python support into the `foxy` branch.

I can run `colcon build && source install/setup.bash && colcon test` in a Docker container with Foxy installed with no errors.

### CODE REVIEW

**Comment by dawsonc** [comment]
@clalancette continuing the conversation from #509; merge conflicts are fixed and the build is passing. What are the next steps for getting a foxy release?

Thanks!

**Comment by dawsonc** [comment]
Hi! Just following up on this PR; it would be great to get a foxy release of this code so we can integrate it in our project. Thanks!

(tagging @clalancette )

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16944/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11509/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17342/)

**Comment by evan-palmer** [comment]
Hello, I wanted to follow up to see the status of this PR. Is there a timeline for when this feature may be merged?

**Comment by clalancette** [comment]
CI did not go well the last time I ran it, and I haven't had time to look into why.  Here is another try just to see if that was a flake:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17437/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11962/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17965/)

**Comment by dawsonc** [comment]
It looks like this issue is happening before it gets to our changes?

```
15:06:26 Recipe: ros2_windows::qt5
15:06:26   * directory[AppData_Qt] action create
15:06:26     - create new directory C:/Users/ContainerAdministrator/AppData\Roaming\Qt
15:06:26   * template[qt-installer.qs] action create
15:06:26     - create new file qt-installer.qs
15:06:26     - update content in file qt-installer.qs from none to d3211e
15:06:26     - suppressed sensitive resource
15:06:26   * windows_package[Qt Install] action install
15:06:26     * remote_file[c:\temp\local-mode-cache\cache\package\qt-opensource-windows-x86-5.12.10.exe] action create[2022-10-03T15:07:05+00:00] WARN: remote_file[c:\temp\local-mode-cache\cache\package\qt-opensource-windows-x86-5.12.10.exe] cannot be downloaded from https://download.qt.io/official_releases/qt/5.12/5.12.10/qt-opensource-windows-x86-5.12.10.exe: 404 "Not Found"
15:06:27 
15:06:27       
15:06:27       ================================================================================
15:06:27       Error executing action `create` on resource 'remote_file[c:\temp\local-mode-cache\cache\package\qt-opensource-windows-x86-5.12.10.exe]'
15:06:27       ================================================================================
15:06:27       
15:06:27       Net::HTTPServerException
15:06:27       ------------------------
15:06:27       404 "Not Found"
15:06:27       
15:06:27       Resource Declaration:
15:06:27       ---------------------
15:06:27       # In c:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.15.22-universal-mingw32/lib/chef/provider/package/windows.rb
15:06:27       
15:06:27       253:           @source_resource ||= build_resource(:remote_file, default_download_cache_path) do
15:06:27       254:             source(new_resource.source)
15:06:27       255:             cookbook_name = new_resource.cookbook_name
15:06:27       256:             checksum(new_resource.checksum)
15:06:27       257:             backup(false)
15:06:27       258: 
15:06:27       259:             # since the source_resource can mutate here, we save off the @source_resource so we can inspect the actual state later
15:06:27       260:             if new_resource.remote_file_attributes
15:06:27       261:               new_resource.remote_file_attributes.each do |(k, v)|
15:06:27       262:                 send(k.to_sym, v)
15:06:27       263:               end
15:06:27       264:             end
15:06:27       265:           end
```

**Comment by clalancette** [comment]
Yeah, that's infrastructure flakiness.  I kicked off a new Windows job.

**Comment by clalancette** [comment]
OK, the remaining warnings on Windows have nothing to do with this.  So going ahead and merging.

**Comment by dawsonc** [comment]
Thanks!

**Pull request merged**
