### PR TITLE
Add Visibility macros to QoS classes

### PR DESCRIPTION
**Pull request by sloretz**
Fixes issue seen in windows debug nightly caused by #160 https://github.com/ros2/geometry2/pull/160#issuecomment-530517512

Windows Debug: [Build Status](https://ci.ros2.org/job/ci_windows/8001/)

Accidentally started Windows build type None, but I don't want to cancel it because of ros2/build_cop#161: [Build Status](https://ci.ros2.org/job/ci_windows/8000/)

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
Looks good to me with green CI.

**Comment by sloretz** [comment]
Windows debug 2 [Build Status](https://ci.ros2.org/job/ci_windows/8003/)

**Comment by sloretz** [comment]
Windows debug 3 [Build Status](https://ci.ros2.org/job/ci_windows/8005/)

**Comment by sloretz** [comment]
CI (testing just tf2_ros)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8121/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4111/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6612/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8006/)

**Review by clalancette — APPROVED** [review]

**Pull request merged**
