### PR TITLE
[Eloquent Backport] add static transform component

### PR DESCRIPTION
**Pull request by allenh1**
This is a backport of #182 for Eloquent.

### CODE REVIEW

**Comment by clalancette** [comment]
I'm hesitant on this.  It doesn't *obviously* break API/ABI from my perspective, but it's a big enough change that I'm somewhat worried about it.  @allenh1 how important is it that you get this into Eloquent?

**Comment by allenh1** [comment]
> It doesn't obviously break API/ABI from my perspective, but it's a big enough change that I'm somewhat worried about it.

I understand your concern for sure.

> @allenh1 how important is it that you get this into Eloquent?

It is used really heavily in a project I was working on previously, and I know the people on that project currently would probably prefer not to continue building a custom tf2 build.

I'd say the importance is somewhere along the lines of "nice to have", and I'll leave it up to your judgement. I also don't see how it could break API/ABI compatibility, but it is definitely not a small change.

**Review by clalancette — APPROVED** [review]
I'm going to approve this for a backport to Eloquent, since there are no obvious API or user-facing breakage in here.  But I'd prefer to get another approval before merging.  Maybe @tfoote or @ahcorde ?

**Comment by sloretz** [comment]
@allenh1 Mind checking if the test failure is caused by this PR? I didn't see any other Eloquent backport PRs have this test fail: http://build.ros2.org/job/Epr__geometry2__ubuntu_bionic_amd64/81/testReport/junit/(root)/tf2_ros/tf2_ros_test_transform_broadcaster_gtest_missing_result/

**Comment by allenh1** [comment]
@sloretz Maybe they are related? The failed tests definitely look suspect. I just rebased on the current `eloquent` branch, as well as built against current `eloquent` debs and ran on my machine.

```
$ build/tf2_ros/tf2_ros_test_static_transform_broadcaster 
[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from tf2_test_static_transform_broadcaster
[ RUN      ] tf2_test_static_transform_broadcaster.transform_broadcaster_rclcpp_node
[       OK ] tf2_test_static_transform_broadcaster.transform_broadcaster_rclcpp_node (19 ms)
[ RUN      ] tf2_test_static_transform_broadcaster.transform_broadcaster_custom_rclcpp_node
[       OK ] tf2_test_static_transform_broadcaster.transform_broadcaster_custom_rclcpp_node (15 ms)
[ RUN      ] tf2_test_static_transform_broadcaster.transform_broadcaster_as_member
[       OK ] tf2_test_static_transform_broadcaster.transform_broadcaster_as_member (16 ms)
[----------] 3 tests from tf2_test_static_transform_broadcaster (50 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test case ran. (50 ms total)
[  PASSED  ] 3 tests.
```

Rather odd... Am I doing something wrong? Just trying to reproduce.

**Comment by clalancette** [comment]
@allenh1 I know this one has sat for a long time, sorry about that.  With Eloquent going out of support in about a month, and the fixes here released into Foxy, what do you want to do with this PR?

**Comment by allenh1** [comment]
@clalancette I think I'll just close this one, not really sure it will be of benefit to anybody at this point.

**Pull request closed without merging**
