### PR TITLE
update to match xml schema

### PR DESCRIPTION
**Pull request by mikaelarguedas**
This updates the package.xml of all packages in this repo that have been ported to ROS2

This change can be submitted upstream along conversion to format 2 for all packages

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Is there a reason to apply the change on the ROS 2 fork first? I would suggest to fill the PR upstream instead, wait until it is merged, and then sync this fork.

**Comment by mikaelarguedas** [comment]
Upstream is still using package format 1 that's why I did it here in the meantime assuming a single PR with conversion to package format 2 + fixing the order of tags will be filled upstream

**Comment by dirk-thomas** [comment]
> assuming a single PR with conversion to package format 2 + fixing the order of tags will be filled upstream

I would rather like to see such a PR against upstream instead of doing "cosmetic" changes like this in our fork (if they are not necessary).

**Comment by mikaelarguedas** [comment]
> I would rather like to see such a PR against upstream instead of doing "cosmetic" changes like this in our fork (if they are not necessary).

Agreed I just don't have time to do this right now and had this fix locally so I just committed it. I'm fine with not merging this and wait for upstream to integrate such changes. May not be trivial to sync with upstream though

**Comment by mikaelarguedas** [comment]
closing this in favor of a future PR to upstream to convert to fromat 2 and fix the xml to match the schema

**Pull request closed without merging**
