### PR TITLE
[Foxy]: backport PR #386

### PR DESCRIPTION
**Pull request by simutisernestas**
Would be nice to backport #386, crashing rviz2 in foxy is getting annoying

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]

**Comment by simutisernestas** [comment]
added same event_found boolean as [here](https://github.com/ros2/geometry2/blob/852ad86fb9fa3bfc955bc73befe42a3093877d7a/tf2_ros/include/tf2_ros/message_filter.h#L486) to fix scope issue

**Comment by clalancette** [comment]
I'm fine with making these changes to Foxy (as you say, they should fix a crash).  However, I think we should change how we are doing this.  Instead of having entirely new commits for these two, I think it would be better here to cherry-pick commits fdc32090 and e813f131.  That will retain original authorship, and should still do what we want here.  @simutisernestas please go ahead and do that and force-push to this PR.

**Comment by simutisernestas** [comment]
Thank you for suggestion @clalancette, much more elegant way to do this

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14667/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9419/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12330/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14810/)

**Comment by clalancette** [comment]
@jacobperron FYI

**Review by jacobperron — APPROVED** [review]

**Pull request merged**
