### PR TITLE
Reenable Eigen tests

### PR DESCRIPTION
**Pull request by gleichdick**
This was separated from #368

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
Looks good, will run CI on it next.

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14702/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9454/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12367/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14846/)

**Comment by gleichdick** [comment]
Shoot, the MSVC error was actually one of my reasons to basically rewrite the whole `convert` stuff...
Guess I'll just reattach this to #427.

**Comment by clalancette** [comment]
> Shoot, the MSVC error was actually one of my reasons to basically rewrite the whole `convert` stuff...
> Guess I'll just reattach this to #427.

Instead of giving up on this whole thing, can we just comment out the problematic statements with a TODO note?  That would still enable more of these tests, and also keep the size of #427 down.

**Comment by gleichdick** [comment]
Okay, sounds reasonable to me. At least the stamped tests should work, because their convert functions don't exsists in the Eigen namespace.

**Pull request closed without merging**
