### PR TITLE
Fix for #589 - Should be able to transform with default timeout

### PR DESCRIPTION
**Pull request by oss-vineet**
As discussed in the issue, this is the fix. I haven't written any tests for this, let me know if I have missed out something.

### CODE REVIEW

**Comment by oss-vineet** [comment]
Since it didn't link in the title - #589

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18705/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13231/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19437/)

**Review by tfoote — APPROVED** [review]
This is a good improvement. It would be great to add a unit test to make sure that this is working and keeps working as expected.

**Comment by oss-vineet** [comment]
> It would be great to add a unit test to make sure that this is working and keeps working as expected.

[ I was about to write a test, when I noticed this. The purpose of writing this line was to suppress this very error right? ](https://github.com/vineet131/geometry2/blob/f5db32ee4607fa7414b4e41f6823219d70d48f0a/tf2_ros/test/test_buffer.cpp#L106) So does just commenting this out work?

**Comment by tfoote** [comment]
You don't want to remove/change that case. The unit tests should validate both cases with and without the dedicated thread. In the case of a dedicated thread both 0 and non-zero timestamps should not error.  In the case of no-dedicated thread, the zero timestamp should not error, but if there's a timeout it should error.

**Comment by oss-vineet** [comment]
@clalancette @ahcorde if the added test is alright with you then this can be merged.

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19162/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13731/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19913/)

**Review by ahcorde — APPROVED** [review]

**Pull request merged**
