### PR TITLE
Fix precision loss from using rclcpp::Time::seconds()

### PR DESCRIPTION
**Pull request by ijnek**
The use of [rclcpp::Time::seconds()](https://github.com/ros2/rclcpp/blob/9ae35e347ead6394d39fc573a1f9af999b5e72a7/rclcpp/include/rclcpp/time.hpp#L196) is causing significant precision loss in the timestamp when using tf2_ros::MessageFilter. One effect of this (among a couple of others) was that it resulted in an [equality comparison](https://github.com/ros2/geometry2/blob/69f78ce84fa621b974417357051146b3620f2051/tf2/src/cache.cpp#L119) of tf time stamps and message header timestamps failing.

It passed all existing tests because the time stamps used in the tests don't get affected by precision loss, but most real use cases of tf2_ros::MessageFilter would have been broken.

By adding a test case that uses `rclcpp::Time(0, 000000001)`, this triggers the precision loss of concern.

This one took me a couple of days... glad it's out of the way. :relieved:

### CODE REVIEW

**Review by aprotyas — APPROVED** [review]
LGTM with green CI.

**Comment by ijnek** [comment]
@SteveMacenski I see tf2_ros::MessageFilter is being used extensively in Nav2, did it always work as intended?

**Comment by ijnek** [comment]
Converting to draft because the test case isn't reliably reproducing the error.

**Comment by ijnek** [comment]
Reopening as a reliable test case was added.

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
building `--up-to test_tf2 tf2_ros` and testing `--select test_tf2 tf2_ros`

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16376/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10985/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16748/)

**Pull request merged**
