### PR TITLE
Address security bug in yaml loading

### PR DESCRIPTION
**Pull request by vmayoral**
Curate bug similar to https://github.com/ros/actionlib/pull/171. 

Connected with https://github.com/aliasrobotics/RVD/issues/2401.

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
Looks good, I'll run CI on this next.

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12162/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7153/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9896/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12052/)

**Comment by clalancette** [comment]
CI is good, merging.  Thanks for the contribution.

**Comment by aprotyas** [comment]
@Mergifyio backport foxy

**Pull request merged**
