### PR TITLE
add torque due to force offset

### PR DESCRIPTION
**Pull request by pac48**
Currently, the `doTransform` function in `tf2_geometry_msgs.hpp` transforms wrenches by applying pure rotation to the force and torque parts separately. However, this does not correspond to transforming a force vector because the transnational component is ignored. So perhaps the function can be renamed `doRotation` or something to that effect. See https://core.ac.uk/download/pdf/154240607.pdf for a reference on transforming force vectors. I made the needed change so `doTransform` now applies a transformation to the given wrench according the method described in the reference I linked.

### CODE REVIEW

**Review by destogl — APPROVED** [review]
Thanks for correcting this!

**Comment by clalancette** [comment]
CI is happy because of style here:

```
Code style divergence in file 'include/tf2_geometry_msgs/tf2_geometry_msgs.hpp':

--- include/tf2_geometry_msgs/tf2_geometry_msgs.hpp
+++ include/tf2_geometry_msgs/tf2_geometry_msgs.hpp.uncrustify
@@ -1189 +1189 @@
-                    transform.transform.translation.z};
+    transform.transform.translation.z};
```

Once that is fixed, we can consider this for inclusion.

**Comment by pac48** [comment]
> 

Thanks for pointing that out. I made the change and it looks like CI is happy now.

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17596/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12137/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18165/)

**Comment by swiz23** [comment]
I saw this change wasn't yet backported to the humble branch. Is that something that's in the pipeline?

**Comment by clalancette** [comment]
> I saw this change wasn't yet backported to the humble branch. Is that something that's in the pipeline?

I can go ahead and do that.

**Comment by clalancette** [comment]
@Mergifyio backport humble

**Pull request merged**
