### PR TITLE
Remove unused setup.py files

### LINKED ISSUE #174: Remove unused setup.py files
There are 4 setup.py files in this repository that look like they are no longer used:

* https://github.com/ros2/geometry2/blob/b2706c5cf3aa761112c15b7f816be89fa63a315e/tf2_kdl/setup.py
* https://github.com/ros2/geometry2/blob/b2706c5cf3aa761112c15b7f816be89fa63a315e/tf2_sensor_msgs/setup.py
* https://github.com/ros2/geometry2/blob/b2706c5cf3aa761112c15b7f816be89fa63a315e/tf2_ros/setup.py
* https://github.com/ros2/geometry2/blob/b2706c5cf3aa761112c15b7f816be89fa63a315e/tf2_geometry_msgs/setup.py

We should remove them as dead code.

### PR DESCRIPTION
**Pull request by vasart**
Closes  #174

### CODE REVIEW

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8605/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4462/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7028/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8525/)

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
Thanks for the contribution!  This is now ready to go, but we'll hold off merging it until after we branch off for Eloquent.

**Comment by dirk-thomas** [comment]
> we'll hold off merging it until after we branch off for Eloquent.

@clalancette Why holding the merge? These are CMake packages - the `setup.py` files are not used anywhere.

**Review by sloretz — APPROVED** [review]

**Comment by tfoote** [comment]
@ros-pull-request-builder retest this please

**Pull request merged**
