### PR TITLE
[foxy backport] Add in pytest.ini so tests succeed locally. (#280)

### PR DESCRIPTION
**Pull request by jacobperron**
Backport #280 to Foxy.

This should help resolve one of the outstanding failures in ros2/ci#503

### CODE REVIEW

**Comment by jacobperron** [comment]
I also had to backport a similar change for the `tf2_ros` Python package (4d60c02). This is a partial backport of the change on the `ros2` branch during the split of CMake and Python packages in #210.

**Comment by jacobperron** [comment]
@ros-pull-request-builder retest this please

**Comment by jacobperron** [comment]
CI for this PR and several other similar backports can be found here: https://github.com/ros2/ci/pull/503#issuecomment-673751744

**Comment by jacobperron** [comment]
I thought https://github.com/ros-infrastructure/ros_buildfarm/pull/828 would resolve the Fpr failure :thinking: 

Maybe it's failing because we've only changed the junit_family option for a subset of the packages being tested in this repo. I can try updating the option for all packages and see what happens.

**Comment by clalancette** [comment]
> Maybe it's failing because we've only changed the junit_family option for a subset of the packages being tested in this repo. I can try updating the option for all packages and see what happens.

Yeah, you need to have it for all of the packages.  This is looking good to me.

**Review by clalancette — APPROVED** [review]

**Pull request merged**
