### PR TITLE
feat: export tf2 sensor msgs target

### PR DESCRIPTION
**Pull request by wep21**
- export tf2 sensor msgs target
- use modern cmake

### CODE REVIEW

**Comment by wep21** [comment]
@clalancette @ahcorde Could anyone review this PR?

**Review by clalancette — APPROVED** [review]
This looks good to me, thanks for the contribution!  I'll run CI on it next.

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16910/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11478/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17312/)

**Comment by wep21** [comment]
@clalancette https://github.com/eProsima/Fast-DDS/pull/2798 fixes CI?

**Comment by clalancette** [comment]
> @clalancette [eProsima/Fast-DDS#2798](https://github.com/eProsima/Fast-DDS/pull/2798) fixes CI?

No idea.  I've been running CI all day and its been succeeding for me until now.  Let's see what happens with that PR.

**Comment by wep21** [comment]
I guess https://github.com/eProsima/Fast-DDS/pull/2579 (merged 3 hours ago) breaks CI and revert the change which breaks CI in https://github.com/eProsima/Fast-DDS/pull/2798.

**Comment by MiguelCompany** [comment]
@wep21 @clalancette eProsima/Fast-DDS#2798 has been merged, and [RDev CI](https://build.ros2.org/job/Rdev__fastrtps__ubuntu_jammy_amd64/51/) has passed

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16911/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11479/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17313/)

**Comment by clalancette** [comment]
@wep21 So, unfortunately, the Eigen dependency here is causing a problem on Windows (it's always Windows).  This also may cause a problem on RHEL and Windows Debug, so we'll also have to run tests there.

I think we need to use some of the workaround that we have in https://github.com/ros2/geometry2/blob/rolling/tf2_eigen_kdl/CMakeLists.txt .  Can you look into it?

**Comment by wep21** [comment]
@clalancette 

> I think we need to use some of the workaround that we have in https://github.com/ros2/geometry2/blob/rolling/tf2_eigen_kdl/CMakeLists.txt . Can you look into it?

I added the workaround for windows in https://github.com/ros2/geometry2/pull/536/commits/8bd1161b867515f6ae1c1e2fe4c968caca4d7ab3.

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16916/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11482/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17315/)

**Review by ahcorde — CHANGES_REQUESTED** [review]
Windows CI is still failing

**Comment by wep21** [comment]
@ahcorde I'm sorry, but I fixed the argument in https://github.com/ros2/geometry2/pull/536/commits/a9bb596aea88dedc011621af8e152d6635bd52f4.
Could you run ci again?

**Comment by clalancette** [comment]
Another run at CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16945/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11510/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17343/)

**Comment by clalancette** [comment]
Windows seems happier with this, which is good progress.  Let's see what RHEL and Windows Debug have to say:

* RHEL [Build Status](http://ci.ros2.org/job/ci_linux-rhel/238/)
* Windows Debug [Build Status](http://ci.ros2.org/job/ci_windows/17344/)

**Comment by clalancette** [comment]
And RHEL and Windows Debug also seem happy.  So I'm going to go ahead and merge; thanks @wep21!

**Review by clalancette — APPROVED** [review]

**Comment by wep21** [comment]
@clalancette Thank you for merging this PR. Is it possible to backport this change to `humble`?

**Pull request merged**
