### PR TITLE
Style fixup in tf2_ros.

### PR DESCRIPTION
**Pull request by clalancette**
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

This is a very large PR, but it enables the linters in the `tf2_ros` package, and then fixes all of the problems that are pointed out.  There should be no functional change from this PR.

### CODE REVIEW

**Comment by clalancette** [comment]
@ros-pull-request-builder retest this please

**Review by ahcorde — APPROVED** [review]
LGTM
I don't know if it makes more sense to include `find_package(ament_lint_auto REQUIRED)` and exclude some tests using:
```
    list(APPEND AMENT_LINT_AUTO_EXCLUDE
      ament_cmake_copyright
    )
```
and configure the other ones using:
```
  set(ament_cmake_cppcheck_LANGUAGE c++)
  set(ament_cmake_uncrustify_ADDITIONAL_ARGS LANGUAGE c++)
  ament_lint_auto_find_test_dependencies()
```

**Comment by clalancette** [comment]
> I don't know if it makes more sense to include `find_package(ament_lint_auto REQUIRED)` and exclude some tests using:

I don't really feel strongly about it either way.  Since you approved, I'm assuming you don't either :).  So I'm just going to leave it for now, hopefully we can go back to using `auto` eventually.

Here is CI for this:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12676/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7639/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10391/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12614/)

**Comment by clalancette** [comment]
All right, CI is green, merging.  Thanks again for the review!

**Comment by SteveMacenski** [comment]
FYI, it looks like these changes removed an include for `tf2_ros Buffer` that has resulted in `gazebo_ros_plugins` and `navigation2` to have to update some files to include it on ros2 master builds to be successful. I imagine other people were caught in this as well and may have some issues requiring explicitly including the header. 

Anywhere including `#include "tf2_ros/transform_listener.h"` but not having ` #include "tf2_ros/buffer.h" ` will need to update to have the buffer include. It looks like in the PR you changed `transform_listener` to include buffer core but not buffer itself which it seems some of us were relying on. 

Leaving this here for posterity if others track back to this for a fix.

**Comment by clalancette** [comment]
> FYI, it looks like these changes removed an include for `tf2_ros Buffer` that has resulted in `gazebo_ros_plugins` and `navigation2` to have to update some files to include it on ros2 master builds to be successful. I imagine other people were caught in this as well and may have some issues requiring explicitly including the header.

That's unfortunate.

> Anywhere including `#include "tf2_ros/transform_listener.h"` but not having `#include "tf2_ros/buffer.h"` will need to update to have the buffer include. It looks like in the PR you changed `transform_listener` to include buffer core but not buffer itself which it seems some of us were relying on.

Yeah, I went through here pretty finely and did "include-what-you-use" on everything.  That included removing things that weren't direct dependencies in the header files.  Ultimately, the downstream consumers probably shouldn't have been relying on this behavior, but it was hard to tell before.  At least it will be clear now.  I hope the breakage isn't *too* widespread.

> Leaving this here for posterity if others track back to this for a fix.

Thanks, appreciate you taking the time to track it back here and leave a note.

**Pull request merged**
