### PR TITLE
tf2 add windows cmath constants

### PR DESCRIPTION
**Pull request by ahcorde**
Including cmath constants in Windonws

### CODE REVIEW

**Review by clalancette — COMMENTED** [review]
There was an earlier discussion about just this sort of problem in https://github.com/ros/urdfdom_headers/pull/34 .  In the end, we decided to go with https://github.com/ros/urdfdom_headers/pull/38 instead, as that will work regardless of the header inclusion order.  I think we probably want a similar patch here, for the same reasons.  Thoughts?

**Comment by ahcorde** [comment]
ros/urdfdom_headers#38 looks cleaner

**Review by clalancette — APPROVED** [review]
Looks good to me with green CI (particularly on Windows).

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9058/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4806/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7404/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8987/)

**Comment by ahcorde** [comment]
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7405/)

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9060/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4808/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7407/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8989/)

**Pull request merged**
