### PR TITLE
Removed obsolete headers

### PR DESCRIPTION
**Pull request by ahcorde**
Removed obsolete headers, these headers are deprecated at least since Humble, it's save to remove them in Rolling

### CODE REVIEW

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20130/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14569/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/20842/)

**Review by clalancette — APPROVED** [review]
It's probably worthwhile to add a release note to http://docs.ros.org/en/rolling/Releases/Release-Jazzy-Jalisco.html as well.

**Comment by ahcorde** [comment]
@clalancette Added note here https://github.com/ros2/ros2_documentation/pull/4138

**Comment by clalancette** [comment]
> @clalancette Added note here [ros2/ros2_documentation#4138](https://github.com/ros2/ros2_documentation/pull/4138)

Thank you!

**Pull request merged**
