### PR TITLE
suppress spam in canTransform

### PR DESCRIPTION
**Pull request by grishalipenko**
suppress spam of "Warning: Invalid frame ..." if timeout > 0 and errstr != nullptr`

### CODE REVIEW

**Comment by grishalipenko** [comment]
resolve https://github.com/ros2/geometry2/issues/501

**Comment by jacobperron** [comment]
I suggest we pass in a temporary string to these calls too, otherwise callers have no choice but to suffer the spam if they call `lookupTransform`:

https://github.com/ros2/geometry2/blob/ef2dd147a25f14ed946c86f5a9fc03c8995d8fbe/tf2_ros/src/buffer.cpp#L94

https://github.com/ros2/geometry2/blob/ef2dd147a25f14ed946c86f5a9fc03c8995d8fbe/tf2_ros/src/buffer.cpp#L117

**Comment by gonzodepedro** [comment]
There are code style [divergences](https://build.ros2.org/job/Rpr__geometry2__ubuntu_jammy_amd64/69/testReport/junit/(root)/projectroot/uncrustify/):

```
--- src/buffer.cpp
+++ src/buffer.cpp.uncrustify
@@ -149,2 +149,3 @@
-    !canTransform(target_frame, source_frame, time,
-                  tf2::Duration(std::chrono::nanoseconds::zero()), errstr) &&
+    !canTransform(
+      target_frame, source_frame, time,
+      tf2::Duration(std::chrono::nanoseconds::zero()), errstr) &&
@@ -178,2 +179,3 @@
-    !canTransform(target_frame, target_time, source_frame, source_time, fixed_frame,
-                  tf2::Duration(std::chrono::nanoseconds::zero()), errstr) &&
+    !canTransform(
+      target_frame, target_time, source_frame, source_time, fixed_frame,
+      tf2::Duration(std::chrono::nanoseconds::zero()), errstr) &&
```

**Comment by jacobperron** [comment]
Replaced by https://github.com/ros2/geometry2/pull/529

**Pull request closed without merging**
