### PR TITLE
Install tf2_geometry_msgs python package

### PR DESCRIPTION
**Pull request by bastinat0r**
I reintroduced the tf2_geometry_msgs python package to be installed, as it seems to work now.

### CODE REVIEW

**Comment by clalancette** [comment]
Are you sure that this works now?  As far as I know, PyKDL hasn't been ported to ament/ROS 2, so I don't think this will work out-of-the-box.

**Comment by bastinat0r** [comment]
Well I did not test in depth, but I needed the functionality and I figured it would at least be useful to create a pull request for other people with the same problem. 
I wanted to convert a PoseStamped into the right coordinate frame and did not find out how to work around the missing package. At least in my use case the tf2_geometry_msgs provides the functionality to do it directly. However, I really just did the one thing until now.

**Comment by clalancette** [comment]
> Well I did not test in depth, but I needed the functionality and I figured it would at least be useful to create a pull request for other people with the same problem.

Right, but as far as I can tell, the script would immediately fail to import `PyKDL` (https://github.com/ros2/geometry2/blob/ros2/tf2_geometry_msgs/scripts/test.py#L5).  So I'm not quite sure what functionality you are currently depending on.  Can you give more information about your environment and what you are doing?

**Comment by bastinat0r** [comment]
I am currently working on [this planning code](https://github.com/ovgu-FINken/driving_swarm_infrastructure/blob/master/src/trajectory_generator/trajectory_generator/direct_planner.py). Interestingly I can import PyKDL, the following snippet shows how I convert the pose (```self.goal``` is of type ```PoseStamped```)
```
        goal = Pose2D()
        try:
            x = self.tfBuffer.transform(self.goal, self.reference_frame)
            goal.x = x.pose.position.x
            goal.y = x.pose.position.y
            goal.theta = yaw_from_orientation(x.pose.orientation)

            self.get_logger().debug(f"got the following for goal position: {goal}")
        except Exception as e: 
            self.get_logger().info(f"Exception in goal transformation {e}")
```

**Comment by clalancette** [comment]
> Interestingly I can import PyKDL

Are you using a mixed ROS 1/ROS 2 environment?  Can you run your python interpreter, and then run:

```
import PyKDL
print(PyKDL.__file__)
```

**Comment by bastinat0r** [comment]
> > Interestingly I can import PyKDL
> 
> Are you using a mixed ROS 1/ROS 2 environment? Can you run your python interpreter, and then run:
> 
> ```
> import PyKDL
> print(PyKDL.__file__)
> ```
```/usr/lib/python3/dist-packages/PyKDL.cpython-38-x86_64-linux-gnu.so```
I installed a fresh ubuntu and I have installed python3-pykdl with apt.

**Comment by clalancette** [comment]
> I installed a fresh ubuntu and I have installed python3-pykdl with apt.

Oh, that's interesting.  I didn't know that package was available in the upstream Ubuntu apt repositories.

The trouble here is that mixing the system installed version of PyKDL with our vendored copy of `orocos_kdl` is dangerous.  If the ABI changes, then it will start crashing and will be tough to debug.  That leaves us with two options:

1.  Stick with our vendored copy of `orocos_kdl`, and re-enable `python_orocos_kdl` ([here](https://github.com/ros2/orocos_kinematics_dynamics/tree/ros2/python_orocos_kdl)).  This guarantees that they match, and continues to work on all platforms (including Windows).
2. Use the apt version of both `orocos_kdl` and `python_orocos_kdl`.  This also guarantees they match, and doesn't require us to build it anymore.  But if we go this route, we need to figure out how to continue to make this work on Windows, which generally involves building a "choco" package for it.

Both options have their pluses and minuses.  The first option is probably the easiest for now, but the second one is attractive because it reduces our maintenance burden.

**Comment by MikeHallettUK** [comment]
Can anyone get python tf2_geometry_msgs (+ PyKDL) working on Intel WINDOWS 10 please ? for NOETIC (and eventually ROS2).

I have it working on WINDOWS 10 in MELODIC... and on Ubuntu with NOETIC... but it currently crashes with PyKDL message in WINDOWS 10 for NOETIC.

Thanks

**Comment by dawsonc** [comment]
Hi!

Has there been any progress towards enabling the `tf2_geometry_msgs` python package? #509 appears to have been merged; would that allow installing `tf2_geometry_msgs` without the PyKDL dependency?

Thanks!

**Comment by clalancette** [comment]
> Has there been any progress towards enabling the `tf2_geometry_msgs` python package? #509 appears to have been merged; would that allow installing `tf2_geometry_msgs` without the PyKDL dependency?

Actually, yes.  With #509 in, we actually no longer need this one, so I'll close this out.

**Pull request closed without merging**
