### PR TITLE
Initialize the quaternion in the tf2_geometry_msgs unit tests

### PR DESCRIPTION
**Pull request by tfoote**
Connects to #24 

 - Linux [Build Status](http://ci.ros2.org/job/ci_linux/2766/)
- Linux aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/299/)
 - OSX [Build Status](http://ci.ros2.org/job/ci_osx/2240/)
 - Windows [Build Status](http://ci.ros2.org/job/ci_windows/2897/)

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
Oh yeah, absolutely.  This has bitten me several times.

**Review by mikaelarguedas — APPROVED** [review]
lgtm, even if we dont do it by default (for performance reasons) we should consider providing a helper function giving zero initialized messages in C and C++...

**Comment by clalancette** [comment]
Honestly, I think we should discuss making the default zero-initialized, and providing a way to not do that for people who are really performance-conscious.  This kind of problem is sneaky and hard to see, and is going to affect everyone developing on ROS2.

**Comment by tfoote** [comment]
@clalancette @mikaelarguedas good idea. ticketed ros2/ros2#367

**Pull request merged**
