### PR TITLE
Allow updating already sent static transforms

### LINKED ISSUE #704: [tf2_ros] Static transforms cannot be overwritten
_Originally posted by @Timple in https://github.com/ros2/geometry2/pull/634#discussion_r1728860271_
            
~Calling `sendTransform` with different values but the same frame_ids get ignored since: https://github.com/ros2/geometry2/pull/634~

~This is a regression from iron to jazzy.~

---
Update https://github.com/ros2/geometry2/pull/705#issuecomment-2332967838

The C++ API should not allow static transforms to be overritten. 
https://github.com/ros2/geometry2/pull/705#issuecomment-2332967838

### PR DESCRIPTION
**Pull request by Timple**
Fixes #704

### CODE REVIEW

**Comment by clalancette** [comment]
So the big reason we put #634 in was because tf2_ros and tf2_ros_py had different semantics here.  #634 was an attempt to make them the same.

I don't have time right now to take a look at this, but whatever we do here we need to make sure that both C++ and Python have the same behavior.

**Comment by Timple** [comment]
Yes, this is the same behavior. In c++ the overwrite happens here: https://github.com/ros2/geometry2/blob/a73160df358c52d1f506fce21f15f8243e9b87f4/tf2_ros/src/static_transform_broadcaster.cpp#L61

**Comment by clalancette** [comment]
I will also make the argument that updating a static transform is....odd.  If it can change, why is it a static transform?

**Comment by Timple** [comment]
Well, it used to work and it works in c++ :slightly_smiling_face: 

But imagine a tool connected to an arm. The tool can be at the tip of the arm or at the toolwall. This rarely changes and it's convenient for late joiners to know the state.

**Comment by sloretz** [comment]
Thank you for the PR! This one got discussed in the triage meeting today 🧇 . The response was the C++ publisher should not allow changes to static transforms either. Of course this can be worked around by deleting and recreating the publisher, but it makes the intent clear that static transforms are expected to be immutable.

I'll close this PR for now, and update #704 to make the C++ API forbid changing the transforms too.

**Comment by scott-robotics** [comment]
Changing static transforms is useful. Consider an online extrinsic calibration which can update static transforms every so often. These are not time-sensitive transforms, we just need the most recent, but they need to be updated.

**Pull request closed without merging**
