### PR TITLE
Allow static_transform_publisher to be run with ros arguments ros2#80

### PR DESCRIPTION
**Pull request by lucasw**

### CODE REVIEW

**Comment by lucasw** [comment]
test_launch.py:
```
from launch import LaunchDescription
  
import launch.actions
import launch_ros.actions


def generate_launch_description():
    launches = []
    launches.append(launch_ros.actions.Node(
            package='tf2_ros',
            node_executable='static_transform_publisher',
            output='screen',
            arguments=['0.1', '0.2', '0.3', '0.4', '.5', '.6', 'map', 'foo'],
            # this doesn't work- it becomes one arg?
            # arguments=['0.1 0.2 0.3 0.4 .5 .6 map foo'],
            ))
    return launch.LaunchDescription(launches)
```
```
ros2 launch test_launch.py
```

```
$ ros2 topic echo /tf_static
transforms:
- header:
    stamp:
      sec: 1542230002
      nanosec: 984828205
    frame_id: map
  child_frame_id: foo
  transform:
    translation:
      x: 0.1
      y: 0.2
      z: 0.3
    rotation:
      x: 0.23366930162788713
      y: 0.28852831022420433
      z: 0.1122402815926294
      w: 0.9217115551320315
```

**Review by tfoote — APPROVED** [review]

**Comment by lucasw** [comment]
@mkhansen-intel I can't run the script in #80 as is I assume because it has functions that don't exist in bouncy.

A variation like this works for me:

```
...
            arguments=['0', '0', '0', '0', '0', '0', 'base_link', 'base_footprint',
                       '__params:=nav2_params.yaml'],
...
```

(setting node_name='foo' in the Node constructor also works fine as long as I edit the yaml node name to match)

The param yaml is in the same dir and I use ros2 launch without a package:
```
ros2 launch test_bringup_launch.py
```

With sim time true or false I get this output, and I can successfully `ros2 param get static_transform_publisher use_sim_time`:

```
ros2 run tf2_ros tf2_echo base_link base_footprint
At time 0.0
- Translation: [0.000, 0.000, 0.000]
- Rotation: in Quaternion [0.000, 0.000, 0.000, 1.000]
...
```

**Comment by lucasw** [comment]
Ideally it would go to both.

**Comment by clalancette** [comment]
> Ideally it would go to both.

Just for your future information, we generally want to apply changes to the development branch (typically 'master' or 'ros2'), and then think about backporting it to older distributions if it applies.  I see @tfoote has already retargetted this one to 'ros2', so I think we're OK here.

**Comment by tfoote** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5626/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2248/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4647/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5516/)

**Comment by lucasw** [comment]
@clalancette I'm fine using my static_tf_args bouncy branch until I upgrade to crystal if there are resource limitations or other reasons not to 'backport'.

**Comment by tfoote** [comment]
There's still an issue with windows that I can't seem to resolve. I reran it with an updated repos file but it's still failing in `test_msgs` which seems unrelated but I can't reproduce on master so I'm going to hold this back for a patch release a little later.

[Build Status](https://ci.ros2.org/job/ci_windows/5520/)

**Comment by clalancette** [comment]
I cleaned up the patch a bit, rebased, and kicked off another build on Windows here: https://ci.ros2.org/job/ci_windows/5571 .  If that is happier, I'll push those changes to this PR.

**Comment by clalancette** [comment]
All right, that last Windows job was happier.  I'm going to push those changes here, kick off another batch of CI (just up to tf2_ros), and then I'm happy to approve/merge.

CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5680/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2285/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4694/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5573/)

**Review by clalancette — APPROVED** [review]
Looks good to me now.  @tfoote , if you have any other concerns, let me know soon, otherwise I'll merge in a bit.

**Comment by lucasw** [comment]
> clalancette force-pushed the lucasw:static_tf_args  branch from b16a4f4 to 95e9987

Now my bouncy build is broken, I didn't realize anyone with upstream permissions could *force push* into my repo until now.  Should I make pre-emptive backup branches or [restrict pull request permissions](https://help.github.com/articles/configuring-protected-branches/) in the future?

In the past for other ros repos I think maintainers would make changes like this separate from the original pr.

**Comment by clalancette** [comment]
>  Should I make pre-emptive backup branches or restrict pull request permissions (I think I can do this) in the future?

You can always get back to the previous commit with `git checkout -b  bouncy b16a4f4`.

That being said, I think the real problem here is that this was based off of the bouncy branch to begin with, and it just didn't have the changes necessary for the ros2 branch.  In the future, I'd suggest working off of the latest ros2/master, then making a separate branch on your repository for any backports you'd like to do.  I think that would avoid problems like this for you.

**Comment by lucasw** [comment]
> You can always get back to the previous commit with git checkout -b bouncy b16a4f4.

```
git clone https://github.com/lucasw/geometry2
cd geometry2
git checkout b16a4f4
error: pathspec 'b16a4f4' did not match any file(s) known to git.
git checkout b16a4f46a50dde1e6d8020c0bfb4aa13c9a43f2e
fatal: reference is not a tree: b16a4f46a50dde1e6d8020c0bfb4aa13c9a43f2e
```

**Comment by tfoote** [comment]
@clalancette Thanks for polishing this up!

@lucasw I'm not sure why it's not working for you. I can check it out after cloning.

```
tfoote@snowman:/tmp Last: [0] (0s Seconds)
$ git clone https://github.com/lucasw/geometry2.git
Cloning into 'geometry2'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 10098 (delta 0), reused 0 (delta 0), pack-reused 10091
Receiving objects: 100% (10098/10098), 2.31 MiB | 0 bytes/s, done.
Resolving deltas: 100% (6292/6292), done.
Checking connectivity... done.
tfoote@snowman:/tmp Last: [0] (2s Seconds)
$ cd geometry2/
tfoote@snowman:/tmp/geometry2 Last: [0] (0s Seconds)
$ git checkout b16a4f46a50dde1e6d8020c0bfb4aa13c9a43f2e
Note: checking out 'b16a4f46a50dde1e6d8020c0bfb4aa13c9a43f2e'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at b16a4f4... Allow static_transform_publisher to be run with ros arguments ros2#80
tfoote@snowman:/tmp/geometry2 Last: [0] (0s Seconds)
$ git checkout b16a4f4
HEAD is now at b16a4f4... Allow static_transform_publisher to be run with ros arguments ros2#80
```

**Comment by lucasw** [comment]
@tfoote I went to a copy of lucasw/geometry2 that hadn't pulled down the results of the force-push and created a new branch [static_tf_args_bouncy](https://github.com/lucasw/geometry2/commits/static_tf_args_bouncy) and pushed that in, now b16a4f46a50dde1e6d8020c0bfb4aa13c9a43f2e is recovered.

**Comment by tfoote** [comment]
@lucasw Could you open a new PR against bouncy with that for review?

**Pull request merged**
