### PR TITLE
Fixed in Exception constructor in tf2_ros

### PR DESCRIPTION
**Pull request by ahcorde**
This PR builds on top of this other PR https://github.com/ros2/geometry2/pull/258. Fix some issues in `tf2_ros`

Signed-off-by: ahcorde <ahcorde@gmail.com>

### CODE REVIEW

**Comment by clalancette** [comment]
The code looks OK to me, but can you explain why this is necessary?  The code in question succeeds in CI, so I'm just curious why we need it now.

**Review by hidmic — APPROVED** [review]
LGTM! 

@clalancette I suspect this patch makes use of [`std::make_exception_ptr`](https://en.cppreference.com/w/cpp/error/make_exception_ptr) in a simpler way, without relying on non-explicit constructors for the given exception type.

**Comment by clalancette** [comment]
> @clalancette I suspect this patch makes use of [`std::make_exception_ptr`](https://en.cppreference.com/w/cpp/error/make_exception_ptr) in a simpler way, without relying on non-explicit constructors for the given exception type.

Yeah, understood.  I'm just not sure what is different about the Fpr environment vs. our CI environment, and if that is something we should look into.

Regardless, this is an improvement over the status-quo, so I'll approve.

**Review by clalancette — APPROVED** [review]
Looks good to me, please also run CI on it.

**Comment by ahcorde** [comment]
Running up-to `geometry2`. Test only for `tf2_ros`

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10825/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6201/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8814/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10710/)

**Pull request merged**
