### PR TITLE
Use orocos_kdl_vendor and orocos-kdl target

### PR DESCRIPTION
**Pull request by cottsay**
Part of ros2/orocos_kdl_vendor#6

### CODE REVIEW

**Comment by clalancette** [comment]
It looks like `tf2_kdl` is still failing to find `Eigen` :(.

**Comment by cottsay** [comment]
The upstream change hasn't been released yet, so the `Rpr` failure is expected.

**Comment by clalancette** [comment]
> The upstream change hasn't been released yet, so the `Rpr` failure is expected.

Ah!  Right.  OK, let me go do a release of that.  We can't merge it quite yet (Rolling is in a sync hold), but we should be able to do that in the next day or so.

**Comment by cottsay** [comment]
If you're itching to get this one merged, the CI jobs I ran on the upstream PR did cover this one as well. So it has been tested. That said, I think we can wait for the sync hold and upstream debian build to happen too.

**Comment by clalancette** [comment]
> If you're itching to get this one merged, the CI jobs I ran on the upstream PR did cover this one as well. So it has been tested. That said, I think we can wait for the sync hold and upstream debian build to happen too.

Yeah, I'd prefer that, otherwise all Rpr jobs on this repository are going to be broken.  I'll do the release now, wait for the sync hold to end, and then merge it in.

**Comment by cottsay** [comment]
> I'll do the release now, wait for the sync hold to end, and then merge it in.

Sounds great. Please release the same change in Humble while you're at it.

**Review by sloretz — APPROVED** [review]

**Comment by clalancette** [comment]
@ros-pull-request-builder retest this please

**Comment by cottsay** [comment]
So this is (not) fun. Looks like the builds on ci.ros2.org don't have `liborocos-kdl-dev` installed and are therefore building from source. The source build appears to define a target, while the debs do not. So the original `orocos_kdl_vendor` change needs to be updated for this to work with the debs.

**Comment by cottsay** [comment]
@ros-pull-request-builder retest this please

**Comment by cottsay** [comment]
@clalancette, the Rpr job is passing now.

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
I know that you ran CI previously, but I think there have been enough changes that another CI run is warranted.  Once that is done, please feel free to merge.

**Comment by cottsay** [comment]
> ...another CI run is warranted.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16878/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11449/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/236/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17279/)

**Comment by cottsay** [comment]
@Mergifyio backport humble

**Pull request merged**
