### PR TITLE
Add tf2::TimePoint <-> builtin_interfaces::msg::Time conversions

### PR DESCRIPTION
**Pull request by dhood**
Connects to ros2/navigation#5
replacement for https://github.com/ros/geometry2/pull/213

### CODE REVIEW

**Comment by clalancette** [comment]
This looks good to me, and should help out my other PR.  I'm going to merge it, thanks!

**Comment by dhood** [comment]
This was mostly opened for visibility so we didn't end up duplicating work, it wasn't necessarily ready for merge. Specifically I hadn't run CI on this to check that it works on windows (as @mikaelarguedas reminded me, this package is in the "core" ros2 repos file so it's important that it works on all platforms even if the changes were made for turtlebot demo purposes).

I'll leave it as is for now and revert if I find any issues when testing, but in the future could you please not merge PRs without CI? We also typically leave it to the opener to decide when a PR is to be merged as they usually have the most context on its state (but that's not a hard rule). Thanks in advance :smile:

**Comment by clalancette** [comment]
Oops, sorry about that.  I wasn't quite sure about that.  I'll definitely do that in the future.

**Comment by mikaelarguedas** [comment]
We also usually squash and merge the PRs. Review them only when they're marked as ready for review and don't merge them without at least the agreement of the opener.

Thanks

**Comment by dhood** [comment]
update: this builds fine on windows. the "dummy robot demo" https://github.com/ros2/demos/pull/118 seems to be publishing static transforms fine on windows (from `tf echo` inspection; I have issues with rviz on my machine). so this PR seems fine to stay merged

**Comment by mikaelarguedas** [comment]
Thanks for testing! I guess https://github.com/ros2/ros2/pull/324 should be merged then so that ci uses this repo

**Comment by dhood** [comment]
windows CI job was [Build Status](http://ci.ros2.org/job/ci_windows/2456/) and then tested manually.

**Comment by mikaelarguedas** [comment]
I think that this job doesn't include these commits does it ?

**Comment by dhood** [comment]
yeah, you're right. as you can see I thought passing geometry2-fork as the branch would be sufficient but it doesn't apply to ros2/ros2. I'll keep testing then!

**Comment by dhood** [comment]
Real CI now:
linux [Build Status](http://ci.ros2.org/job/ci_linux/2355/)
OSX [Build Status](http://ci.ros2.org/job/ci_osx/1809/)
windows [Build Status](http://ci.ros2.org/job/ci_windows/2463/)

and I have tested that the dummy robot demo works fine on windows. so I again conclude (for real this time) that this PR is good to stay merged

**Comment by clalancette** [comment]
Thanks Deanna, I appreciate it.  Sorry for the breach in protocol; I'll do better for next time.

**Comment by dhood** [comment]
no worries! :smile:

**Pull request merged**
