### PR TITLE
[Eloquent backport] tf2 add windows cmath constants

### PR DESCRIPTION
**Pull request by ahcorde**
tf2 add windows cmath constants

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
Seems reasonable, but do you know why automated CI is failing?

**Comment by ahcorde** [comment]
The tests which are failing are in tf2_ros. We didn't backport these tests https://github.com/ros2/geometry2/pull/202 to Eloquent.

**Comment by clalancette** [comment]
> The tests which are failing are in tf2_ros. We didn't backport these tests #202 to Eloquent.

Hm, OK.  I'd suggest that we disable those tests in this PR (since they aren't going to pass anyway), then do a follow-up to backport #202 to Eloquent.  Does that make sense?

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9134/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4856/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7458/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9056/)

**Comment by ahcorde** [comment]
In the CI the tests are passing: 

```
14:17:05 7: [==========] Running 3 tests from 1 test case.
14:17:05 7: [----------] Global test environment set-up.
14:17:05 7: [----------] 3 tests from tf2_test_transform_broadcaster
14:17:05 7: [ RUN      ] tf2_test_transform_broadcaster.transform_broadcaster_rclcpp_node
14:17:05 7: [       OK ] tf2_test_transform_broadcaster.transform_broadcaster_rclcpp_node (10 ms)
14:17:05 7: [ RUN      ] tf2_test_transform_broadcaster.transform_broadcaster_custom_rclcpp_node
14:17:05 7: [       OK ] tf2_test_transform_broadcaster.transform_broadcaster_custom_rclcpp_node (3 ms)
14:17:05 7: [ RUN      ] tf2_test_transform_broadcaster.transform_broadcaster_as_member
14:17:05 7: [       OK ] tf2_test_transform_broadcaster.transform_broadcaster_as_member (3 ms)
14:17:05 7: [----------] 3 tests from tf2_test_transform_broadcaster (16 ms total)
14:17:05 7: 
14:17:05 7: [----------] Global test environment tear-down
14:17:05 7: [==========] 3 tests from 1 test case ran. (16 ms total)
14:17:05 7: [  PASSED  ] 3 tests.
14:17:05 7: -- run_test.py: return code 0
14:17:05 7: -- run_test.py: inject classname prefix into gtest result file '/home/jenkins-
```

But here a timeout has raised

```
23:44:14 7: Test timeout computed to be: 60
23:44:14 7: -- run_test.py: invoking following command in '/tmp/ws/src/geometry2/tf2_ros':
23:44:14 7:  - /tmp/ws/build_isolated/tf2_ros/tf2_ros_test_transform_broadcaster --gtest_output=xml:/tmp/ws/test_results/tf2_ros/tf2_ros_test_transform_broadcaster.gtest.xml
23:44:14 7: [==========] Running 3 tests from 1 test case.
23:44:14 7: [----------] Global test environment set-up.
23:44:14 7: [----------] 3 tests from tf2_test_transform_broadcaster
23:44:14 7: [ RUN      ] tf2_test_transform_broadcaster.transform_broadcaster_rclcpp_node
23:44:14 7: [       OK ] tf2_test_transform_broadcaster.transform_broadcaster_rclcpp_node (4 ms)
23:44:14 7: [ RUN      ] tf2_test_transform_broadcaster.transform_broadcaster_custom_rclcpp_node
23:44:14 7: [       OK ] tf2_test_transform_broadcaster.transform_broadcaster_custom_rclcpp_node (2 ms)
23:44:14 7: [ RUN      ] tf2_test_transform_broadcaster.transform_broadcaster_as_member
23:45:14  7/10 Test  #7: tf2_ros_test_transform_broadcaster ..........***Timeout  60.00 sec
23:45:14 test 8
23:45:14       Start  8: tf2_ros_test_time_reset
```

**Comment by clalancette** [comment]
Hm.  Well, I doubt that issue is from this PR, so I'd say let's ticket that issue to look at and fix later, and go ahead and merge this one.

**Review by clalancette — APPROVED** [review]

**Comment by ahcorde** [comment]
https://github.com/ros2/geometry2/issues/228

**Pull request merged**
