### PR TITLE
Fix the time_jump_callback signature.

### LINKED ISSUE #710: time jump post_callback called with wrong number of arguments
## Bug report

This manifests as a crash in an rqt plugin through tf2_ros, but i have reason to believe the actual issue lies in rclpy... It seems like the time jump callback gets called incorrectly:

```
jonasotto@ade ➜  workspace rqt --ros-args -p use_sim_time:=True                                                                                                                 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-jonasotto'
Traceback (most recent call last):
  File "/opt/ros/jazzy/lib/python3.12/site-packages/rqt_gui_py/rclpy_spinner.py", line 32, in run
    executor.spin_once(timeout_sec=1.0)
  File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/executors.py", line 899, in spin_once
    self._spin_once_impl(timeout_sec)
  File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/executors.py", line 896, in _spin_once_impl
    future.result()  # raise any exceptions
    ^^^^^^^^^^^^^^^
  File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/task.py", line 94, in result
    raise self.exception()
  File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/task.py", line 239, in __call__
    self._handler.send(None)
  File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/executors.py", line 508, in handler
    await call_coroutine()
  File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/executors.py", line 396, in _execute
    await await_or_execute(sub.callback, *msg_tuple)
  File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/executors.py", line 111, in await_or_execute
    return callback(*args)
           ^^^^^^^^^^^^^^^
  File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/time_source.py", line 128, in clock_callback
    clock.set_ros_time_override(time_from_msg)
  File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/clock.py", line 364, in set_ros_time_override
    self.handle.set_ros_time_override(time._time_handle)
  File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/clock.py", line 242, in callback_shim
    original_callback(TimeJump(clock_change, duration))
TypeError: Buffer.time_jump_callback() takes 1 positional argument but 2 were given
[1]    295333 IOT instruction (core dumped)  rqt --ros-args -p use_sim_time:=True
```

The callback does actually only take 1 argument (https://github.com/ros2/geometry2/blob/jazzy/tf2_ros_py/tf2_ros/buffer.py#L107), but at least according to the type hints that should be correct (https://github.com/ros2/rclpy/blob/jazzy/rclpy/rclpy/clock.py#L221)... Not sure what goes wrong here.

- Operating System:
  - Ubuntu 24.04
- Installation type:
  - debian packages
- Version or commit hash:
  - rclpy 7.1.2 in ros 2 jazzy
- DDS implementation:
  - default
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue
* run rqt with sim-time enabled (`rqt --ros-args -p use_sim_time:=True`), open tf tree visualization
* run rosbag replay with tf data and clock (`ros2 bag play --clock 100 ...`)
* restart rosbag replay
* observe crash

#### Expected behavior
Time jump callbacks called correctly, resulting action taken (tf buffer clear etc)

#### Actual behavior
Crash during execution of time jump callback

### PR DESCRIPTION
**Pull request by clalancette**
Because it accesses object data, the first argument must be 'self'.

This should fix #710

### CODE REVIEW

**Comment by clalancette** [comment]
@ottojo it would be helpful if you could test this out and report on whether it fixes the issue for you.

**Review by sloretz — APPROVED** [review]

**Comment by ottojo** [comment]
> @ottojo it would be helpful if you could test this out and report on whether it fixes the issue for you.

this fixes the problem all the way to rqt-tf-tree in jazzy! now i get 
```
[WARN] [1727982819.603705139] [tf2_buffer]: Detected jump back in time. Clearing tf buffer.
```
when without the fix rqt would crash, as expected.

thanks for the quick fix!

**Comment by clalancette** [comment]
> thanks for the quick fix!

That is all @sloretz looking into it: I just typed "self" in my editor :).

In any case, thanks for the quick test.  I'll run CI on this, and assuming that is successful merge it and backport it to Jazzy.

**Comment by clalancette** [comment]
Pulls: https://github.com/ros2/geometry2/pull/711
Gist: https://gist.githubusercontent.com/clalancette/62b268b1728630fd52a7f87c87408a16/raw/8f6226d64d310487f277fc9ed6364e93ef2fa148/ros2.repos
BUILD args:  --packages-above-and-dependencies tf2_ros_py
TEST args:  --packages-above tf2_ros_py
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14655
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21940/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16207/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1457/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22667/)

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport jazzy

**Pull request merged**
