### PR TITLE
Added support for `LifecycleNode` to `TransformBroadcaster` and `Stat…

### PR DESCRIPTION
**Pull request by Myzhar**
…icTransformBroadcaster`

Tried to replicate the "latch" behaviour for `/tf_static` in `StaticTransformBroadcaster`

### CODE REVIEW

**Comment by Myzhar** [comment]
A possible solution for https://github.com/ros2/geometry2/issues/70

**Review by tfoote — CHANGES_REQUESTED** [review]
Please separate your pull request into separate logical items for review. The lifecycle support and latching behavior are completely separate issues and would be easier to review separately. Best would be separate pull requests, at minimum they should be two different commits in this PR.

Also please provide more documentation of what you're doing and how. "Tried to replicate the "latch" behaviour for /tf_static in StaticTransformBroadcaster" is pretty vague and offhand. Do you think that this is good enough to merge or is it a prototype that needs iteration? I would also like to see some unit tests that validate the new code paths that are being added so we can make sure that there's not a regression in the future and they actually do what we want it to do.

There's also a lot of unnecessary whitespace changes clutter up the diff. And you appear to have reindented the code. The combination of these makes the diff much harder to review and will break any other outstanding branches or pull requests unnecessarily. To that end please roll those changes back.

**Comment by cottsay** [comment]
@Myzhar, it looks like there hasn't been any activity on this PR for a while now. Are you able to iterate based on the provided feedback?

**Comment by Myzhar** [comment]
@cottsay I have not too much time now. If there is not anyone that can work on this, I can try, but I cannot guarantee... let me know

**Comment by Karsten1987** [comment]
@Myzhar Can this be closed? I believe with the latest change in https://github.com/ros2/geometry2/pull/108 this should be resolved.

**Comment by Myzhar** [comment]
Amazing. I can't wait to test the new ROS2 release.
I'm sorry I have no time to test the preview release.

**Pull request closed without merging**
