### PR TITLE
allow construction of tf broadcaster from node object (not a pointer)

### LINKED ISSUE #554: TransformBroadcaster takes shared pointer instead of raw node
## Bug report

**Required Info:**

- Operating System: Ubuntu 22.04 Jammy
- Installation type: Source
- Version or commit hash: rolling
- DDS implementation: Rolling Default

### Description

The [TransformBroadcaster constructor](https://github.com/ros2/geometry2/blob/d6559f955c3f9de3360d35e10373d7c44185db4a/tf2_ros/include/tf2_ros/transform_broadcaster.h#L59) should take a ``NodeT``, but tests in [tf2_ros/test/test_transform_broadcaster.cpp](https://github.com/ros2/geometry2/blob/d6559f955c3f9de3360d35e10373d7c44185db4a/tf2_ros/test/test_transform_broadcaster.cpp) pass a pointer to a rclcpp::Node to the broadcaster (and the tests pass although they shouldn't).

Changes in https://github.com/ros2/geometry2/pull/552 exposed this issue, as it depends on ``NodeT`` being a pointer to a rclcpp::Node.

In [Writing a broadcaster (C++)](https://docs.ros.org/en/rolling/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Broadcaster-Cpp.html), a node instance is passed to the constructor as below:

```cpp
tf_broadcaster_ = std::make_unique<tf2_ros::TransformBroadcaster>(*this);
```

But in the [tf2_ros/test/test_transform_broadcaster.cpp](https://github.com/ros2/geometry2/blob/d6559f955c3f9de3360d35e10373d7c44185db4a/tf2_ros/test/test_transform_broadcaster.cpp#L53), a shared pointer is provided.

```cpp
TEST(tf2_test_transform_broadcaster, transform_broadcaster_rclcpp_node)
{
  auto node = rclcpp::Node::make_shared("tf2_ros_message_filter");

  tf2_ros::TransformBroadcaster tfb(node);
}
```

This was originally reported in https://github.com/ros-perception/image_pipeline/issues/775.

FYI @alsora 

#### Steps to reproduce issue

```
mkdir -p geometry2_ws/src
cd "$_"
git clone git@github.com:ijnek/geometry2 -b ijnek-bug-test-case
cd ../
colcon build
```

#### Expected behavior

Compiles fine.

#### Actual behavior

Doesn't compile.

```
--- stderr: tf2_ros                               
In file included from /home/ijnek/tmp_workspaces/geometry2_ws/src/geometry2/tf2_ros/test/test_transform_broadcaster.cpp:31:
/home/ijnek/tmp_workspaces/geometry2_ws/src/geometry2/tf2_ros/include/tf2_ros/transform_broadcaster.h: In instantiation of ‘tf2_ros::TransformBroadcaster::TransformBroadcaster(NodeT&&, const rclcpp::QoS&, const rclcpp::PublisherOptionsWithAllocator<AllocatorT>&) [with NodeT = rclcpp::Node&; AllocatorT = std::allocator<void>]’:
/home/ijnek/tmp_workspaces/geometry2_ws/src/geometry2/tf2_ros/test/test_transform_broadcaster.cpp:57:41:   required from here
/home/ijnek/tmp_workspaces/geometry2_ws/src/geometry2/tf2_ros/include/tf2_ros/transform_broadcaster.h:71:7: error: base operand of ‘->’ has non-pointer type ‘rclcpp::Node’
   71 |       node->get_node_parameters_interface(),
      |       ^~~~
gmake[2]: *** [CMakeFiles/tf2_ros_test_transform_broadcaster.dir/build.make:76: CMakeFiles/tf2_ros_test_transform_broadcaster.dir/test/test_transform_broadcaster.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:510: CMakeFiles/tf2_ros_test_transform_broadcaster.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< tf2_ros [14.3s, exited with code 2]
```

### PR DESCRIPTION
**Pull request by alsora**
Follow up PR to https://github.com/ros2/geometry2/pull/552.
Addresses https://github.com/ros2/geometry2/issues/554

### CODE REVIEW

**Comment by alsora** [comment]
@clalancette @ijnek I ended up taking a different approach to address the problem.
This does not require to add/deprecate constructors.
I added a unit-test to verify that we can build both from pointers as well as non-pointers.

**Review by jacobperron — APPROVED** [review]
LGTM
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17391/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11923/)
* Windows [Build Status](https://ci.ros2.org/job/ci_windows/17903/)

**Comment by jacobperron** [comment]
Bizarre, I'm not sure why Windows is experiencing build errors.

**Review by ijnek — APPROVED** [review]
LGTM, added tests look good too.

**Comment by clalancette** [comment]
> Bizarre, I'm not sure why Windows is experiencing build errors.

Well, at the very least it does look like there are some standard header includes missing in the `rclcpp` node_interface headers.  I've opened up https://github.com/ros2/rclcpp/pull/2018 to fix that, which may also fix this.

**Comment by clalancette** [comment]
All right, I've merged in the rclcpp PR (thanks @alsora for the review).  Let's see if it fixes CI here:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17413/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11940/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17917/)

**Review by clalancette — APPROVED** [review]
This looks good to me, and has green CI.

I also verified that it fixes the test case that @ijnek had on his branch.  So I'm going to go ahead and merge this, thanks for the fix!

**Comment by ijnek** [comment]
Thanks @alsora for taking on the work!

**Pull request merged**
