### PR TITLE
MessageFilter Generalizated Nodes

### LINKED ISSUE #95: Lifecycle node support for tf2_ros::MessageFilter
#### Feature description
Similar to #70 and #94, the MessageFilter class needs support for lifecycle nodes. 

#### Implementation considerations
There could be a constructor that takes the required node interfaces, perhaps in addition to rclcpp::Node and rclcpp_lifecycle::LifecycleNode.

### PR DESCRIPTION
**Pull request by CursedRock17**
This PR should entirely resolve #95 as pull request #96 didn't use a templated `Node` in the `MessageFilter` constructors. There were concerns of:
> Retain[ing] the existing node-based interface for backwards compatibility.

which we can do with defaulted templated `Nodes` and `node_interface` methods.

### CODE REVIEW

**Comment by ahcorde** [comment]
@clalancette what do you think about this?

> which we can do with defaulted templated Nodes and node_interface methods.

I can see both strategies in some other packages, any recomendation ?

**Review by ahcorde — CHANGES_REQUESTED** [review]
conflicts

**Comment by sloretz** [comment]
@CursedRock17 friendly ping to rebase the PR 🧇

**Comment by CursedRock17** [comment]
@sloretz after I saw issue #698, I began writing a fix which would essentially make this PR obsolete. Is it even still worth cleaning up and merging this in, if it's going to be deprecated in the future, I would feel it to be a dead feature.

**Comment by clalancette** [comment]
> @sloretz after I saw issue #698, I began writing a fix which would essentially make this PR obsolete. Is it even still worth cleaning up and merging this in, if it's going to be deprecated in the future, I would feel it to be a dead feature.

Agreed with your reasoning.  In that case, I'm going to close this out.  But feel free to reopen if you think we should pursue this.

**Pull request closed without merging**
