### PR TITLE
tf2_eigen_kdl: add ament_cmake_gtest as test_depend

### PR DESCRIPTION
**Pull request by JafarAbdi**
Fix: https://github.com/ros2/geometry2/pull/311#issuecomment-713867008

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
This is obviously the correct thing to do, so I'll approve and run CI on it.  We'll find out overnight if it fixes the problem.

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12828/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7784/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10541/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12772/)

**Comment by cottsay** [comment]
Here is a rebuild of @clalancette's Linux build with only CycloneDDS enabled: [Build Status](https://ci.ros2.org/job/ci_linux/12829/)
Here is the same configuration building master, which fails as expected: [Build Status](https://ci.ros2.org/job/ci_linux/12827/)

**Comment by clalancette** [comment]
@ros-pull-request-builder retest this please

**Review by cottsay — APPROVED** [review]

**Comment by clalancette** [comment]
Cool, looks like all tests are green here.  Merging, thanks for the quick fix @JafarAbdi .

**Pull request merged**
