### PR TITLE
Add wait time option to view_frames

### PR DESCRIPTION
**Pull request by jacobperron**
Sometimes the default 5 seconds is not enough time to collect all TF
data. The new command-line option let's the user change the time to
wait when collecting TF frame information from the system.

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]
Do we neeed to include `python3-argparse` as a `<exec_depend>` in the `package.xml` ?

**Comment by clalancette** [comment]
> Do we neeed to include `python3-argparse` as a `<exec_depend>` in the `package.xml` ?

It shouldn't be necessary; `argparse` is builtin in python3 (as far as I know).

**Review by clalancette — APPROVED** [review]
Looks good to me with green CI.

**Comment by jacobperron** [comment]
> > Do we neeed to include python3-argparse as a <exec_depend> in the package.xml ?

> It shouldn't be necessary; argparse is builtin in python3 (as far as I know).

Yeah, I don't think it is necessary. I don't see any of our other packages declaring a dependency on `argparse`.

**Comment by jacobperron** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13628/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8510/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11343/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13690/)

**Pull request merged**
