### PR TITLE
Compile fix for upcomming changes to rclcpp::Executor

### PR DESCRIPTION
**Pull request by jmachowinski**
Needs to be merge before https://github.com/ros2/rclcpp/pull/2382

### CODE REVIEW

**Review by fujitatomoya — APPROVED** [review]
lgtm with green CI. (thanks for the refactoring.)

**Comment by jmachowinski** [comment]
@fujitatomoya can we merge this ?

We don't need to merge 2382 prior to this.

**Comment by ahcorde** [comment]
> @fujitatomoya can we merge this ?
> 
> We don't need to merge 2382 prior to this.

Sure, let me launch CI

**Review by ahcorde — APPROVED** [review]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20800/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15103/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21478/)

**Review by ahcorde — CHANGES_REQUESTED** [review]
Do you mind to check the new warnings?

**Comment by jmachowinski** [comment]
I'll look into it tomorrow.

**Comment by jmachowinski** [comment]
@ahcorde fixed

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20808/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15112/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21492/)

**Review by ahcorde — APPROVED** [review]

**Pull request merged**
