### PR TITLE
add a bridge mapping rule so tf/tfMessage maps to tf2_msgs/TFMessage

### PR DESCRIPTION
**Pull request by wjwwood**
I did this according to this doc:

https://github.com/ros2/ros1_bridge/blob/master/doc/index.rst#how-can-i-install-mapping-rule-files

And some help from @dirk-thomas.

I tested this with our HSR demo.

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
Seems good to me.  Nice to know about the mapping rules :).

**Review by mikaelarguedas — APPROVED** [review]
thanks for fixing this! that was a known issue we didnt find time to address and test during beta3.
I was originally concerned that the custom mapping rule would override the mapping of tf2/TFMessage but looking at the code it's just adding custom mappings to the default ones :+1:

**Review by dhood — APPROVED** [review]
added a comment in the mapping file (not necessary, but can't hurt), hope you don't mind

**Comment by wjwwood** [comment]
lgtm, thanks @dhood.

**Comment by mikaelarguedas** [comment]
@wjwwood should this be merged ?

**Comment by wjwwood** [comment]
Yeah, thanks for the reminder.

**Pull request merged**
