### PR TITLE
Adding static transform listener

### PR DESCRIPTION
**Pull request by ayrton04**
Addressses #662.

I went with @clalancette's suggestion and just added a `static_only` parameter (with a default of `false`) to the constructors and the `init` method.

However, that made things slightly awkward, for two reasons:

1. In order to specify `static_only`, we have to now specify a ton of other optional parameters.
2. If we are setting `static_only` to `true`, we now have to specify parameters for the behaviour of the _dynamic_ transform subscriber, even though it won't be used. That felt clunky.

So in addition to the above, I also created a "convenience" class, `StaticTransformListener`. It inherits from `TransformListener` and has equivalent constructors (but without the dynamic subscriber parameters). It simply calls the base `TransformListener` constructor with the required parameters, using dummy values for the dynamic transform subscriber options and QoS.

In addition, I added tests:

1. I added tests that were exactly equivalent to the `TransformListener` tests, which seem largely aimed at just constructing listeners, rather than using them.
2. I added a new test that has a `TransformListener` and a `StaticTransformListener`. We publish dynamic and static transforms, and then check to see if the respective dynamic and static buffers have the transforms we expect.

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20948/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15240/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21622/)

**Comment by ahcorde** [comment]
@clalancette any comments on this one ?

**Comment by sloretz** [comment]
@clalancette friendly ping 🧇

**Comment by ahcorde** [comment]
@clalancette do you mind to take a look ?

**Comment by ahcorde** [comment]
friendly ping @clalancette

**Comment by ayrton04** [comment]
Hello! Not wanting to be difficult at all, but as we're approaching the 3-month mark for this PR, it would be really great if we could either approve it or reject it. If we're not happy with the overall implementation, I am happy to change it (or just close the PR, if we feel this changes too much).

Thanks!

**Comment by ahcorde** [comment]
friendly ping @clalancette

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21748/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16023/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1253/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22451/)

**Comment by araitaiga** [comment]
@ahcorde Would it be possible to backport this change to the jazzy branch as well?
We have a use case on Jazzy where this improvement would help.

**Comment by ahcorde** [comment]
@araitaiga we can backport this but it will require some rework. Because this is breaking ABI. We need to keep the old signature to keep backward ABI compatibility.

For example for one of the `TransformListener` constructor:

```cpp
// Keep the original symbol exactly as it was
explicit TransformListener(tf2::BufferCore & buffer, bool spin_thread = true);

// Add a brand new symbol for the new functionality
explicit TransformListener(tf2::BufferCore & buffer, bool spin_thread, bool static_only);
```

Happy to review the PR If you move forward.

**Comment by araitaiga** [comment]
@ahcorde Thanks for the reply! I'd like to work on a PR to backport this to jazzy with ABI compatibility. Just to confirm: is it the right approach to branch off from the current jazzy branch and manually re-implement these changes in an ABI-compatible way?

**Comment by ahcorde** [comment]
> @ahcorde Thanks for the reply! I'd like to work on a PR to backport this to jazzy with ABI compatibility. Just to confirm: is it the right approach to branch off from the current jazzy branch and manually re-implement these changes in an ABI-compatible way?

yes, you can do it manually

**Comment by araitaiga** [comment]
Thank you confirming. I'll create the PR.

**Pull request merged**
